version: 2

jobs:
    builddeb:
        docker:
            - image: debian
        environment:
            DEBEMAIL "contact@whitewaterfoundry.com"
            DEBFULLNAME "Whitewater Foundry, Ltd. Co."
        steps:
            - checkout
            - run:
                name: Ensure we have debuild installed
                command: |
                    echo "deb http://ftp.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/stretch-backports.list
                    apt-get -y -q update
                    apt-get -y -q install -t stretch-backports devscripts debhelper
            - run:
                name: Build the package
                command: debuild -i -us -uc -b

workflows:
    version: 2
    build:
        jobs:
            - builddeb