version: 2

jobs:
    builddeb:
        docker:
            - image: debian:testing
        environment:
            DEBEMAIL "contact@whitewaterfoundry.com"
            DEBFULLNAME "Whitewater Foundry, Ltd. Co."
        steps:
            - checkout
            - run:
                name: Ensure we have debuild installed
                command: |
                    apt-get -y -q update
                    apt-get -y -q install devscripts debhelper 
            - run:
                name: Set version
                command: |
                    sed "s/0.1-1/0.1-${CIRCLE_BUILD_NUM}/" ./debian/changelog
            - run:
                name: Build the package
                command: debuild -i -us -uc -b
            - run:
                name: Create workspace
                command: mkdir -p /tmp/pkgs
            - run:
                name: Copy package to workspace
                command: cp ../wlinux-setup_0.1-1_all.deb /tmp/pkgs/wlinux-setup_0.1-${CIRCLE_BUILD_NUM}_all.deb
            - persist_to_workspace:
                root: /tmp/pkgs
                paths: .
    deploydeb:
        docker:
            - image: circleci/ruby:2.3-jessie
        steps:
            - attach_workspace:
                 at: /tmp/pkgs
            - run:
                name: Install packageloud cli
                command: gem install package_cloud
            - run:
                name: Push deb package
                command: |
                    PKGLOCATION="/tmp/pkgs/wlinux-setup_0.1-${CIRCLE_BUILD_NUM}_all.deb"
                    package_cloud push whitewaterfoundry/wlinux-setup/debian/buster ${PKGLOCATION}
workflows:
    version: 2
    build:
        jobs:
            - builddeb
            - deploydeb:
                requires:
                    - builddeb
