version: 2

jobs:
    builddeb:
        docker:
            - image: debian
        environment:
            DEBEMAIL "contact@whitewaterfoundry.com"
            DEBFULLNAME "Whitewater Foundry, Ltd. Co."
        steps:
            - checkout
            - run:
                name: Ensure we have debuild installed
                command: |
                    echo "deb http://ftp.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/stretch-backports.list
                    apt-get -y -q update
                    apt-get -y -q install -t stretch-backports devscripts debhelper
            - run:
                name: Build the package
                command: |
                    debuild -i -us -uc -b
                    mkdir -p /tmp/pkgs
                    cp ../wlinux-setup_0.1-1_all.deb /tmp/pkgs
            - store_artifacts:
                path: /tmp/pkgs
    deploydeb:
        machine: true
        steps:
            - run:
                name: Install packagecloud CLI
                command: gem install package_cloud
            - run:
                name: Push deb package
                command: package_cloud push whitewaterfoundry/wlinux-setup/debian/stretch /tmp/pkgs/wlinux-setup_0.1-1_all.deb

workflows:
    version: 2
    build:
        jobs:
            - builddeb
            - deploydeb:
                requires:
                    - builddeb
